{
 "title": "Pod Metrics",
 "description": "Dashboard to visualize data from the NVIDIA Data Center GPU Manager (DCGM)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "pvcs",
    "query": {
     "query": "label_values(kube_pod_spec_volumes_persistentvolumeclaims_info{pod=\"$pod\"}, persistentvolumeclaim)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP{exported_pod=\"$pod\"}, gpu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Metrics Overview $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\", image!=\"\", container!~\"(istio.*|^$)\"}[5m]))) / avg(kube_pod_container_resource_limits_cpu_cores{pod=\"$pod\", container!~\"(istio.*|^$)\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{pod=\"$pod\", image!=\"\", container!~\"(istio.*|^$)\"}) / avg(kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\", container!~\"(istio.*|^$)\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "CPUs" } },
   "yaxes": [
    { "format": "CPUs" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=\"$pod\", container!~\"(istio.*|^$)\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container!~\"(istio.*|^$)\"}",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$pod\", image!=\"\", container!~\"(istio.*|^$)\"}[5m]))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=\"$pod\", container!~\"(istio.*|^$)\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"$pod\", container!~\"(istio.*|^$)\"}",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\", image!=\"\", container!~\"(istio.*|^$)\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "Download"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[1m]))",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Total Container Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=\"$pod\", container!~\"(istio.*|^$)\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=\"$pod\", container!~\"(istio.*|^$)\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Pod Logs $pod",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{pod=\"$pod\", container!~\"(istio.*|^$)\"}",
     "legendFormat": "test"
    }
   ]
  },
  { "title": "Persistent Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "PVC Usage: $pvcs",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "repeat": "pvcs",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"$pvcs\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvcs\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "GPU Metrics $gpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "gpu" },
  {
   "title": "GPU $gpu Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{exported_pod=\"$pod\", gpu=\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU $gpu Mem Cpy Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{exported_pod=\"$pod\", gpu=\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU $gpu Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{exported_pod=\"$pod\", gpu=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "GPU $gpu Mem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{exported_pod=\"$pod\", gpu=\"$gpu\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{exported_pod=\"$pod\", gpu=\"$gpu\"} + DCGM_FI_DEV_FB_FREE{exported_pod=\"$pod\", gpu=\"$gpu\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GPU $gpu SM Clocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_SM_CLOCK{exported_pod=\"$pod\", gpu=\"$gpu\"} * 10^6)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU $gpu Memory Clocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_MEM_CLOCK{exported_pod=\"$pod\", gpu=\"$gpu\"} * 10^6)",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU $gpu Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{exported_pod=\"$pod\", gpu=\"$gpu\"})",
     "legendFormat": "Power Usage"
    }
   ]
  }
 ]
}