{
 "title": "Knative - Reconciler",
 "description": "Knative - Reconciler",
 "tags": [ "Knative" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "reconciler",
    "label": "Reconciler",
    "query": "label_values(knative_dev_internal_serving_controller_reconcile_count, reconciler)"
   },
   {
    "name": "key",
    "label": "Key",
    "query": "label_values(knative_dev_internal_serving_controller_reconcile_count{reconciler=\"$reconciler\"}, key)"
   }
  ]
 },
 "panels": [
  { "title": "Aggregate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconcile Count (per min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (reconciler)(60 * rate(knative_dev_internal_serving_controller_reconcile_count[1m]))",
     "legendFormat": "{{reconciler}}"
    }
   ]
  },
  { "title": "Per Reconciler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$reconciler Reconcile Count (per min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60 * rate(knative_dev_internal_serving_controller_reconcile_count{reconciler=\"$reconciler\"}[1m]))",
     "legendFormat": "{{reconciler}}"
    }
   ]
  },
  {
   "title": "$reconciler Reconcile Latency Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(knative_dev_internal_serving_controller_reconcile_latency_bucket{reconciler=\"$reconciler\"}[1m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(knative_dev_internal_serving_controller_reconcile_latency_bucket{reconciler=\"$reconciler\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(knative_dev_internal_serving_controller_reconcile_latency_bucket{reconciler=\"$reconciler\"}[1m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  { "title": "Per Reconciler & Key", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "$reconciler/$key Reconcile Count (per min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60 * rate(knative_dev_internal_serving_controller_reconcile_count{reconciler=\"$reconciler\", key=\"$key\"}[1m]))",
     "legendFormat": "{{reconciler}}"
    }
   ]
  },
  {
   "title": "$reconciler/$key Reconcile Latency Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(knative_dev_internal_serving_controller_reconcile_latency_bucket{reconciler=\"$reconciler\", key=\"$key\"}[1m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(knative_dev_internal_serving_controller_reconcile_latency_bucket{reconciler=\"$reconciler\", key=\"$key\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(knative_dev_internal_serving_controller_reconcile_latency_bucket{reconciler=\"$reconciler\", key=\"$key\"}[1m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  }
 ]
}